# logfilename                            [owner:group]  mode  count  size  when  flags
/Users/ken/logs/audiobook-watch.log       ken:staff      644   5     1000  *     NZ
/tmp/audiobook-watch.log                  ken:wheel      644   5     1000  *     NZ
/tmp/audiobook-join.log                   ken:wheel      644   5     500   *     NZ
/tmp/audiobook-tags.log                   ken:wheel      644   5     500   *     NZ
